pipeline {
    agent {
        label 'agent'
    }

    stages {

        stage('Checkout') {
            steps {
                echo 'Downloading code'
                sh 'invalid-command'
            }
        }

        stage('Build') {
            steps {
                sh 'hostname'
                sh 'pwd'
                sh 'ls -la'
            }
        }

        stage('Test') {
            steps {
                echo 'Running tests'
            }
        }
    }
}
