pipeline {
    agent any

    stages {

        stage('Credentials Demo') {
            steps {

                withCredentials([
                    string(
                        credentialsId: 'my-secret',
                        variable: 'SECRET'
                    )
                ]) {

                    sh 'echo Secret Loaded'
                    sh 'echo $SECRET'
                }
            }
        }
    }
}
