pipeline {
    agent {
        label 'agent'
    }

    stages {

        stage('Checkout') {
             steps {
                checkout scm
            }
        }

        stage('Install') {
            steps {
                dir('jenkins-file') {
                    sh 'npm install'
                }
            }
        }

        stage('Test') {
            steps {
                dir('jenkins-file') {
                    sh 'npm test'
                }
            }
        }

        stage('Build') {
            steps {
                dir('jenkins-file') {
                    sh 'npm run build'
                }
            }
        }
    }
}
